name: plum-recipe-backend
apiVersion: v1
home: https://github.com/hmcts/cnp-plum-recipes-service
version: 0.5.0
description: HMCTS Plum recipes service (test application)
maintainers:
  - name: HMCTS CNP Team
    email: cnpteam@hmcts.net
