dependencies:
  - name: java
    version: ~2.11.2
    repository: '@hmctspublic'
  - name: bulk-scan
    version: ~0.1.2
    repository: '@hmctspublic'
  - name: postgresql
    version: ~6.3.5
    repository: '@stable'
    condition: plum.postgresql.enabled
