java:
  applicationPort: 4550
  readinessPath: '/health/readiness'
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_SSL_MODE: disable
    POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    DUMMY: "DummyVar2"
  aadIdentityName: cnp
  # Don't modify below here
  image: 'https://hmctspublic.azurecr.io/plum/recipe-backend:latest'
