java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_DATABASE: "plum"
    POSTGRES_USER: "hmcts"
    POSTGRES_PASSWORD: "hmcts"
postgresql:
  ## Disable Postgres Persistence
  persistence:
    enabled: false
  ## Default Postgres Configuration parameters
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: plum
  enabled: false #java chart postgres disabled
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "user-profile" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "bulk_scan" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
global:
  idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl: idam-web-public.aat.platform.hmcts.net
  ccdDataStoreUrl: "http://ccd-data-store"
ccd:
  postgresql:
    enabled: false
  rpeServiceAuthProvider:
    enabled: true
  draftStoreService:
    enabled: false
  dmStore:
    enabled: false
  paymentApi:
    enabled: false
  managementWeb:
    enabled: false
  apiGatewayWeb:
    enabled: false
  adminWeb:
    enabled: false
  printService:
    enabled: false
  activityApi:
    enabled: false
  testStubsService:
    enabled: false
bulkscan:
  ccd:
    enabled: true
  postgresql:
    enabled: false

plum:
  postgresql:
    enabled: true
