java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  readinessPath: '/health/readiness'
  postgresql:
    enabled: true
  disableKeyVaults: true
  environment:
    POSTGRES_SSL_MODE: disable
