postgresql:
  enabled: false

camunda-bpm:
  enabled: false

java:
  applicationPort: 4550
  readinessPath: '/health/readiness'
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_SSL_MODE: disable
    POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    DUMMY: "DummyVar2"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  # Don't modify below here
  image: 'https://hmctspublic.azurecr.io/plum/recipe-backend:latest'
