java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_SSL_MODE: require
  aadIdentityName: cnp
  keyVaults:
    "plumsi":
      resourceGroup: plum-shared-infrastructure
      secrets:
        - recipe-backend-POSTGRES-DATABASE-v11
        - recipe-backend-POSTGRES-HOST-v11
        - recipe-backend-POSTGRES-USER-v11
        - recipe-backend-POSTGRES-PASS-v11
