java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  postgresql:
    enabled: true
  disableKeyVaults: true
  environment:
    POSTGRES_SSL_MODE: disable
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
    POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"

elasticsearch:
  clusterName: "es"
  replicas: 1
  minimumMasterNodes: 1
  antiAffinity: "soft"
  esJavaOpts: "-Xmx512m -Xms512m"
  persistence:
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    path: /
    hosts:
      - ""