java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  postgresql:
    enabled: false
  disableKeyVaults: true
  secrets:
    POSTGRES_PASSWORD:
      secretRef: test-server-pr-1
      key: PASSWORD
  environment:
    POSTGRES_SSL_MODE: require
    POSTGRES_DATABASE: "{{ .Release.Name }}"
    POSTGRES_USER: "hmcts"
    POSTGRES_HOST: "test-server-pr-1.postgres.database.azure.com"
