java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_USER: hmcts
    POSTGRES_PASSWORD: hmcts

postgresql:
  enabled: true
  image:
    tag: '11.3.0'
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE camunda WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE javadatabase WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  persistence:
    enabled: false

camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    releaseNameOverride: ${SERVICE_NAME}-camunda
    ingressHost: camunda-${SERVICE_FQDN}
    environment:
      CAMUNDA_DB_HOST: "{{ .Release.Name }}-postgresql"
      CAMUNDA_DB_NAME: camunda
      CAMUNDA_DB_USER_NAME: hmcts
      CAMUNDA_DB_PASSWORD: hmcts
      CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: true
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      CAMUNDA_DB_CONN_OPTIONS: ""