java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  postgresql:
    enabled: true
    initdbScripts:
      init.sql: |-
        CREATE DATABASE "camunda" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;

camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    releaseNameOverride: ${SERVICE_NAME}-camunda
    ingressHost: camunda-${SERVICE_FQDN}
    environment:
      CAMUNDA_DB_HOST: "{{ .Release.Name }}-postgresql"
      CAMUNDA_DB_NAME: camunda
      CAMUNDA_DB_USER_NAME: "{{ .Values.postgresql.postgresqlUsername}}"
      CAMUNDA_DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
      CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: true
      SPRING_FLYWAY_ENABLED: false
      SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
      CAMUNDA_DB_CONN_OPTIONS: ""
    postgresql:
      enabled: true