java:
  applicationPort: 4550
  readinessPath: '/health/readiness'
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_SSL_MODE: require
    POSTGRES_DATABASE: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
  # Don't modify below here
  image: 'hmctspublic.azurecr.io/plum/recipe-backend:latest'
