java:
  applicationPort: 4550
  aadIdentityName: cnp
  readinessPath: '/health/readiness'
  # Don't modify below here
  image: 'hmctspublic.azurecr.io/plum/recipe-backend:latest'
  environment:
    POSTGRES_SSL_MODE: require
  autoscaling:
    enabled: false
    enabledForDevMode: true
    maxReplicas: 5
    cpu:
      enabled: false
  keyVaults:
    "plumsi":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE-v11
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST-v11
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER-v11
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS-v11
          alias: POSTGRES_PASSWORD
