java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  postgresql:
    enabled: true
  disableKeyVaults: true
  secrets:
    POSTGRES_PASSWORD:
      secretRef: {{ .Release.Name }}-postgresql
      key: PASSWORD
  environment:
    #POSTGRES_SSL_MODE: disable
    POSTGRES_DATABASE: "{{ .Release.Name }}"
    POSTGRES_USER: "hmcts"
    POSTGRES_HOST: "{{ .Release.Name }}.postgres.database.azure.com"
