java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  readinessPath: '/health/readinessfail'
  postgresql:
    enabled: true
  disableKeyVaults: true
  environment:
    POSTGRES_SSL_MODE: disable
    POSTGRES_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    POSTGRES_DATABASE: "{{ .Values.postgresql.auth.database }}"
    POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
