java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  postgresql:
    enabled: true
  keyVaults:
    "plumsi":
      secrets:
        - recipe-backend-POSTGRES-PASS-TEST
