java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    "plumsi":
      resourceGroup: plum-shared-infrastructure
      secrets:
        - recipe-backend-POSTGRES-DATABASE
        - recipe-backend-POSTGRES-HOST
        - recipe-backend-POSTGRES-USER
        - recipe-backend-POSTGRES-PASS
