#{{- $password := randAlphaNum 20 | lower | nospace -}}
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersDatabase
metadata:
  name: {{ .Release.Name }}
  namespace: cnp
spec:
  owner:
    name: cnp-server-preview
  charset: utf8
#---
#apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
#kind: FlexibleServer
#metadata:
#  name: cnp-server-preview
#  namespace: cnp
#spec:
#  owner:
#    name: cft-aso-test-postgresql  #created ahead and added to flux
#  location: uksouth
#  version: "11"
#  sku:
#    name: Standard_B1ms
#    tier: Burstable
#  administratorLogin: hmcts
#  administratorLoginPassword:
#    name: cnp-server-preview-aso-postgresql
#    key: PASSWORD
#  storage:
#    storageSizeGB: 32
#  network:
#    delegatedSubnetResourceReference:
#      armId: /subscriptions/8b6ea922-0862-443e-af15-6056e1c9b9a4/resourceGroups/cft-preview-network-rg/providers/Microsoft.Network/virtualNetworks/cft-preview-vnet/subnets/flexiblepostgresql
#    privateDnsZoneArmResourceReference:
#      armId: /subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/resourceGroups/core-infra-intsvc-rg/providers/Microsoft.Network/privateDnsZones/privatelink.postgres.database.azure.com
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: cnp-server-preview-aso-postgresql
#  namespace: cnp
#stringData:
#  USERNAME: "hmcts"
#  PASSWORD: M8eF4Qcg&EfF
#  SERVER:   cnp-server-preview.postgres.database.azure.com
#  PORT:     "5432"
