{{- $password := randAlphaNum 20 | lower | nospace -}}
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServer
metadata:
  name: {{ .Release.Name }}
  namespace: cnp
spec:
  owner:
    name: cft-aso-test-postgresql # created ahead
  location: uksouth
  version: "11"
  sku:
    name: Standard_B1ms
    tier: Burstable
  administratorLogin: hmcts
  administratorLoginPassword:
    name: {{ .Release.Name }}-aso-postgresql
    key: PASSWORD
  storage:
    storageSizeGB: 32
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersDatabase
metadata:
  name: {{ .Release.Name }}
  namespace: cnp
spec:
  owner:
    name: {{ .Release.Name }}
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersFirewallRule
metadata:
  name: {{ .Release.Name }}
  namespace: cnp
spec:
  owner:
    name: {{ .Release.Name }}
  # The following address range allows anybody to connect to this server.
  # This should only be used for demo purposes and not in production!
  # There are other ways to control server access which are not covered here, you can see more about it here:
  # https://docs.microsoft.com/azure/postgresql/flexible-server/concepts-security#network-security
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aso-postgresql
  namespace: cnp
stringData:
  USERNAME: "hmcts"
  PASSWORD: {{ $password }}
  DATABASE: {{ .Release.Name }}
  SERVER:   {{ .Release.Name }}.postgres.database.azure.com
  PORT:     "5432"
