java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_SSL_MODE: require
    CLUSTER_NAME: cft-sbox-00-aks
  serviceAccountName: crumble
  saEnabled: true